spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mp?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: warn
    com.lwx.mybatisplus.mapper: trace
  pattern:
    console:'%p%m%n'
mybatis-plus:
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.lwx.mybatisplus.domain